// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":return img`
2 2 2 2 2 2 2 2 
. . . 2 2 . . . 
. . . 2 2 . . . 
. . 2 . . 2 . . 
. 2 . . . . 2 . 
. 2 . . . . 2 . 
2 . . . . . . 2 
2 2 2 2 2 2 2 2 
`;
            case "image3":return img`
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
`;
            case "image5":return img`
. d d f f f . . 
. d d d d d . . 
2 2 8 2 2 8 2 . 
2 8 5 8 8 5 2 . 
d 8 8 8 8 8 d . 
. 8 8 8 8 8 . . 
. 8 8 . 8 8 . . 
. e e . e e . . 
`;
            case "image6":return img`
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. 2 2 2 1 . . . 
. 2 2 2 2 2 2 2 
. e e d d d . . 
. d d f d f . . 
. d d d d d d . 
`;
            case "image4":return img`
c b b b b b b c 
b c c c c c c b 
c b b b b b b c 
c c c c c c c c 
b c c c c c c b 
c b b b b b b c 
c c c c c c c c 
b c c c c c c b 
`;
            case "image1":return img`
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
.22222................
....9.22222...........
....9......22222......
....9...........222...
......................
......................
..c.9.........2222222.
.fc.9..2222222........
.222222...............
......................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
