// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
......................
......................
........6666..........
.ee.....9999..........
.ee.....9999..........
.ee.....9999..........
.22222222222222222262.
...................9..
...................9..
................22222.
........26222222......
...22222.9............
.........9............
.........9............
.22222...9............
......22222222........
..............22222...
......................
......................
................22222.
........22222222......
...22622..............
.....9................
.....9................
.22222................
....9.22222...........
....9......22222......
....9...........222...
......................
......................
..8.9.........2222222.
.f8.9..2222222........
.222222...............
......................
`;
            case "image2":return img`
2 2 2 2 2 2 2 2 
. . . 2 2 . . . 
. . . 2 2 . . . 
. . 2 . . 2 . . 
. 2 . . . . 2 . 
. 2 . . . . 2 . 
2 . . . . . . 2 
2 2 2 2 2 2 2 2 
`;
            case "image3":return img`
8 6 6 6 6 6 6 8 
6 8 8 8 8 8 8 6 
8 6 6 6 6 6 6 8 
8 8 8 8 8 8 8 8 
6 8 8 8 8 8 8 6 
8 6 6 6 6 6 6 8 
8 8 8 8 8 8 8 8 
6 8 8 8 8 8 8 6 
`;
            case "image4":return img`
9 9 9 9 9 9 9 9 
9 . . 2 2 . . 9 
9 9 9 9 9 9 9 9 
9 . 2 . . 2 . 9 
9 9 9 9 9 9 9 9 
9 2 . . . . 2 9 
9 9 9 9 9 9 9 9 
9 2 2 2 2 2 2 9 
`;
            case "image5":return img`
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
`;
            case "image6":return img`
. . d d d d . . 
. e e e e e e . 
. 8 8 8 8 8 8 . 
. e e e e e e . 
. 8 8 8 8 8 8 . 
. e e e e e e . 
. 8 8 8 8 8 8 . 
. . d d d d . . 
`;
            case "image7":return img`
. d d f f f . . 
. d d d d d . . 
8 8 2 8 8 2 8 . 
8 2 d 2 2 d 8 . 
d 2 2 2 2 2 d . 
. 2 2 2 2 2 . . 
. 2 2 . 2 2 . . 
. 8 8 . 8 8 . . 
`;
            case "image8":return img`
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. 2 2 2 1 . . . 
. 2 2 2 2 2 2 2 
. 8 8 d d d . . 
. d d f d f . . 
. d d d d d d . 
`;
            case "image9":return img`
................................................................
................................................................
................................................................
................................................................
................eeeeeee.........................................
...............eeeeeeeee........................................
..............eeddeeeddee.......................................
.............eeedddeddddee......................................
............eeeddddeddddde......................................
...........deeddd11d11ddde......ddd.............................
..........ddeeedd1ede1ddeedd...ddfddd...........................
..........dddeedddddddddeedd..ddfdddfd..........................
.........eeeddddddeeedddddd....fffdfdd..........................
.......eeeedd11ddddddddd11dd...dddfddd..........................
......eeeeed111e111e111e111d....ddddede.........................
....eeeeeeedde1ee1eee1eee1ed.......eeee.........................
...eeeeeeeeedd1e111e111e11de......eeeee.........................
..eeeeefeeeeeddd111d111dddeeeeeeeeeeeeee........................
..eeeeeeffeeeeedddddddddeeeeeeeeeeeeeeee........................
..eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee........................
..eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee........................
...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........................
....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........................
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............................
......eeeeeeeeeeeeeeeeeeeeeeeeeeeee.............................
.........eeeeeeeeeeeeeeeeeeeeeeee...............................
.......eeeeeeeeeeeeeeeeeeeeeeeee................................
.....eeeeeeeeeee................................................
....eeeeeeeeeee.................................................
....eeeeeeeeeee.................................................
....eeeeeeeeeee.................................................
....eeeeeeeeee..eeeee...........................................
...eeeeeeeeeeeee................................................
.dddeeeeeee.....................................................
ddedddeeee......................................................
dddddedddd......................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image10":return img`
......................
......................
........6666..........
.ee.....9999..........
.ee.....9999..........
.ee.....9999..........
.22222222222222222262.
...................9..
...................9..
................22222.
........26222222......
...22222.9............
.........9............
.........9............
.22222...9............
......22222222........
..............22222...
......................
......................
................22222.
........22222222......
...22622..............
.....9................
.....9................
.22222................
....9.22222...........
....9......22222......
....9...........222...
......................
......................
..8.9.........2222222.
.f8.9..2222222........
.222222...............
......................
`;
            case "image11":return img`
2 2 2 2 2 2 2 2 
. . . 2 2 . . . 
. . . 2 2 . . . 
. . 2 . . 2 . . 
. 2 . . . . 2 . 
. 2 . . . . 2 . 
2 . . . . . . 2 
2 2 2 2 2 2 2 2 
`;
            case "image12":return img`
8 6 6 6 6 6 6 8 
6 8 8 8 8 8 8 6 
8 6 6 6 6 6 6 8 
8 8 8 8 8 8 8 8 
6 8 8 8 8 8 8 6 
8 6 6 6 6 6 6 8 
8 8 8 8 8 8 8 8 
6 8 8 8 8 8 8 6 
`;
            case "image13":return img`
9 9 9 9 9 9 9 9 
9 . . 2 2 . . 9 
9 9 9 9 9 9 9 9 
9 . 2 . . 2 . 9 
9 9 9 9 9 9 9 9 
9 2 . . . . 2 9 
9 9 9 9 9 9 9 9 
9 2 2 2 2 2 2 9 
`;
            case "image14":return img`
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
9 9 9 9 9 9 9 9 
9 . . . . . . 9 
`;
            case "image15":return img`
. . d d d d . . 
. e e e e e e . 
. 8 8 8 8 8 8 . 
. e e e e e e . 
. 8 8 8 8 8 8 . 
. e e e e e e . 
. 8 8 8 8 8 8 . 
. . d d d d . . 
`;
            case "image16":return img`
. d d f f f . . 
. d d d d d . . 
8 8 2 8 8 2 8 . 
8 2 d 2 2 d 8 . 
d 2 2 2 2 2 d . 
. 2 2 2 2 2 . . 
. 2 2 . 2 2 . . 
. 8 8 . 8 8 . . 
`;
            case "image17":return img`
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. 2 2 2 1 . . . 
. 2 2 2 2 2 2 2 
. 8 8 d d d . . 
. d d f d f . . 
. d d d d d d . 
`;
            case "image18":return img`
..............eeeeeee.................
.............eeeeeeeee................
............eeddeeeddee...............
...........eeedddeddddee..............
..........eeeddddeddddde..............
.........deeddd11d11ddde......ddd.....
........ddeeedd1ede1ddeedd...ddfddd...
........dddeedddddddddeedd..ddfdddfd..
.......eeeddddddeeedddddd....fffdfdd..
.....eeeedd11ddddddddd11dd...dddfddd..
....eeeeed111e111e111e111d....ddddede.
..eeeeeeedde1ee1eee1eee1ed.......eeee.
.eeeeeeeeedd1e111e111e11de......eeeee.
eeeeefeeeeeddd111d111dddeeeeeeeeeeeeee
eeeeeeffeeeeedddddddddeeeeeeeeeeeeeeee
eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee
eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee
.eeeeeeeeeedddddeedddddeeeeeeeeeeeeee.
..eeeeeeeeedddddffdddddeeeeeeeeeeeee..
...eeeeeeeedddddffdddddeeeeeeeeeee....
....eeeeeeedddddffdddddeeeeeeeeee.....
.......eeeedddffddffdddeeeeeeee.......
.....eeeeeeeffddddddffeeeeeeee........
...eeeeeeeeeeddddddddeeeeeeeee........
..eeeeeeeeeeeeddddddeeeeeeeeee........
..eeeeeeeeeeeeddddddeeeeeeeeee........
..eeeeeeeeeeeeeddddeeeeeeeeeeee.......
..eeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.eeeeeeeeeeeee.....eeeeeeeeeeeeee.....
ddeeeeeee...........eeeeeeeeeeeeee....
edddeeee.............eeeeeeeeeeeee....
dddedddd..............eeeeeeeeeeee....
......................eeeeeeeeeee.....
......................eeeeeeeeeee.....
.......................dedddeeedded...
.......................ddedddddedded..
........................ddddddddddded.
`;
            case "image19":return img`
.................eeeeeee..............
................eeeeeeeee.............
...............eeddeeeddee............
..............eeddddedddeee...........
..............edddddeddddeee..........
.....ddd......eddd11d11dddeed.........
...dddfdd...ddeedd1ede1ddeeedd........
..dfdddfdd..ddeedddddddddeeddd........
..ddfdfff....ddddddeeeddddddeee.......
..dddfddd...dd11ddddddddd11ddeeee.....
.ededddd....d111e111e111e111deeeee....
.eeee.......de1eee1eee1ee1eddeeeeeee..
.eeeee......ed11e111e111e1ddeeeeeeeee.
eeeeeeeeeeeeeeddd111d111dddeeeeefeeeee
eeeeeeeeeeeeeeeedddddddddeeeeeffeeeeee
eeeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeee
eeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeee
.eeeeeeeeeeeeeedddddeedddddeeeeeeeeee.
..eeeeeeeeeeeeedddddffdddddeeeeeeeee..
....eeeeeeeeeeedddddffdddddeeeeeeee...
.....eeeeeeeeeedddddffdddddeeeeeee....
.......eeeeeeeedddffddffdddeeee.......
........eeeeeeeeffddddddffeeeeeee.....
........eeeeeeeeeddddddddeeeeeeeeee...
........eeeeeeeeeeddddddeeeeeeeeeeee..
........eeeeeeeeeeddddddeeeeeeeeeeee..
.......eeeeeeeeeeeeddddeeeeeeeeeeeee..
......eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..
.....eeeeeeeeeeeeee.....eeeeeeeeeeeee.
....eeeeeeeeeeeeee...........eeeeeeedd
....eeeeeeeeeeeee.............eeeeddde
....eeeeeeeeeeee..............ddddeddd
.....eeeeeeeeeee......................
.....eeeeeeeeeee......................
...deddeeeddded.......................
..deddedddddedd.......................
.deddddddddddd........................
`;
            case "image20":return img`
..............eeeeeee.................
.............eeeeeeeee................
............eeddeeeddee...............
...........eeedddeddddee..............
..........eeeddddeddddde..............
.........deeddd11d11ddde......ddd.....
........ddeeedd1ede1ddeedd...ddfddd...
........dddeedddddddddeedd..ddfdddfd..
.......eeeddddddeeedddddd....fffdfdd..
.....eeeedd11ddddddddd11dd...dddfddd..
....eeeeed111e111e111e111d....ddddede.
..eeeeeeedde1ee1eee1eee1ed.......eeee.
.eeeeeeeeedd1e111e111e11de......eeeee.
eeeeefeeeeeddd111d111dddeeeeeeeeeeeeee
eeeeeeffeeeeedddddddddeeeeeeeeeeeeeeee
eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee
eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee
.eeeeeeeeeedddddeedddddeeeeeeeeeeeeee.
..eeeeeeeeedddddffdddddeeeeeeeeeeeee..
...eeeeeeeedddddffdddddeeeeeeeeeee....
....eeeeeeedddddffdddddeeeeeeeeee.....
.......eeeedddffddffdddeeeeeeee.......
.....eeeeeeeffddddddffeeeeeeee........
...eeeeeeeeeeddddddddeeeeeeeee........
..eeeeeeeeeeeeddddddeeeeeeeeee........
..eeeeeeeeeeeeddddddeeeeeeeeee........
..eeeeeeeeeeeeeddddeeeeeeeeeeee.......
..eeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.eeeeeeeeeeeee.....eeeeeeeeeeeeee.....
ddeeeeeee...........eeeeeeeeeeeeee....
edddeeee.............eeeeeeeeeeeee....
dddedddd..............eeeeeeeeeeee....
......................eeeeeeeeeee.....
......................eeeeeeeeeee.....
.......................dedddeeedded...
.......................ddedddddedded..
........................ddddddddddded.
`;
            case "image21":return img`
..............eeeeeee.................
.............eeeeeeeee................
............eeddeeeddee...............
...........eeedddeddddee..............
..........eeeddddeddddde..............
.........deeddd11d11ddde......ddd.....
........ddeeedd1ede1ddeedd...ddfddd...
........dddeedddddddddeedd..ddfdddfd..
.......eeeddddddeeedddddd....fffdfdd..
.....eeeedd11ddddddddd11dd...dddfddd..
....eeeeed111e111e111e111d....ddddede.
..eeeeeeedde1ee1eee1eee1ed.......eeee.
.eeeeeeeeedd1e111e111e11de......eeeee.
eeeeefeeeeeddd111d111dddeeeeeeeeeeeeee
eeeeeeffeeeeedddddddddeeeeeeeeeeeeeeee
eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee
eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee
.eeeeeeeeeedddddeedddddeeeeeeeeeeeeee.
..eeeeeeeeedddddffdddddeeeeeeeeeeeee..
...eeeeeeeedddddffdddddeeeeeeeeeee....
....eeeeeeedddddffdddddeeeeeeeeee.....
.......eeeedddffddffdddeeeeeeee.......
.....eeeeeeeffddddddffeeeeeeee........
...eeeeeeeeeeddddddddeeeeeeeee........
..eeeeeeeeeeeeddddddeeeeeeeeee........
..eeeeeeeeeeeeddddddeeeeeeeeee........
..eeeeeeeeeeeeeddddeeeeeeeeeeee.......
..eeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.eeeeeeeeeeeee.....eeeeeeeeeeeeee.....
ddeeeeeee...........eeeeeeeeeeeeee....
edddeeee.............eeeeeeeeeeeee....
dddedddd..............eeeeeeeeeeee....
......................eeeeeeeeeee.....
......................eeeeeeeeeee.....
.......................dedddeeedded...
.......................ddedddddedded..
........................ddddddddddded.
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
