namespace SpriteKind {
    export const donkey = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySpritebottom.isHittingTile(CollisionDirection.Bottom) || mySpritebottom.tileKindAt(TileDirection.Center, assets.tile`transparency16`)) {
        mySpritebottom.vy = -70
    }
})
let mySpritebottom: Sprite = null
scene.setTileMap(img`
    ......................
    ......................
    ........6666..........
    .ee.....9999..........
    .ee.....9999..........
    .ee.....9999..........
    .22222222222222222262.
    ...................9..
    ...................9..
    ................22222.
    ........26222222......
    ...22222.9............
    .........9............
    .........9............
    .22222...9............
    ......22222222........
    ..............22222...
    ......................
    ......................
    ................22222.
    ........22222222......
    ...22622..............
    .....9................
    .....9................
    .22222................
    ....9.22222...........
    ....9......22222......
    ....9...........222...
    ......................
    ......................
    ..8.9.........2222222.
    .f8.9..2222222........
    .222222...............
    ......................
    `, TileScale.Eight)
scene.setTile(2, img`
    2 2 2 2 2 2 2 2 
    . . . 2 2 . . . 
    . . . 2 2 . . . 
    . . 2 . . 2 . . 
    . 2 . . . . 2 . 
    . 2 . . . . 2 . 
    2 . . . . . . 2 
    2 2 2 2 2 2 2 2 
    `, true)
scene.setTile(8, img`
    8 6 6 6 6 6 6 8 
    6 8 8 8 8 8 8 6 
    8 6 6 6 6 6 6 8 
    8 8 8 8 8 8 8 8 
    6 8 8 8 8 8 8 6 
    8 6 6 6 6 6 6 8 
    8 8 8 8 8 8 8 8 
    6 8 8 8 8 8 8 6 
    `, false)
scene.setTile(6, img`
    9 9 9 9 9 9 9 9 
    9 . . 2 2 . . 9 
    9 9 9 9 9 9 9 9 
    9 . 2 . . 2 . 9 
    9 9 9 9 9 9 9 9 
    9 2 . . . . 2 9 
    9 9 9 9 9 9 9 9 
    9 2 2 2 2 2 2 9 
    `, false)
scene.setTile(9, img`
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    `, false)
scene.setTile(14, img`
    . . d d d d . . 
    . e e e e e e . 
    . 8 8 8 8 8 8 . 
    . e e e e e e . 
    . 8 8 8 8 8 8 . 
    . e e e e e e . 
    . 8 8 8 8 8 8 . 
    . . d d d d . . 
    `, false)
mySpritebottom = sprites.create(img`
    . d d f f f . . 
    . d d d d d . . 
    8 8 2 8 8 2 8 . 
    8 2 d 2 2 d 8 . 
    d 2 2 2 2 2 d . 
    . 2 2 2 2 2 . . 
    . 2 2 . 2 2 . . 
    . 8 8 . 8 8 . . 
    `, SpriteKind.Player)
mySpritebottom.ay = 100
scene.cameraFollowSprite(mySpritebottom)
controller.moveSprite(mySpritebottom, 50, 0)
let mySpriteTop = sprites.create(img`
    . . . . . . . . 
    . . . . . . . . 
    . . . . . . . . 
    . 2 2 2 1 . . . 
    . 2 2 2 2 2 2 2 
    . 8 8 d d d . . 
    . d d f d f . . 
    . d d d d d d . 
    `, SpriteKind.Player)
mySpriteTop.setFlag(SpriteFlag.GhostThroughWalls, true)
mySpriteTop.setFlag(SpriteFlag.GhostThroughTiles, true)
mySpriteTop.setFlag(SpriteFlag.GhostThroughSprites, true)
let donkeykong = sprites.create(img`
    ..............eeeeeee.................
    .............eeeeeeeee................
    ............eeddeeeddee...............
    ...........eeedddeddddee..............
    ..........eeeddddeddddde..............
    .........deeddd11d11ddde......ddd.....
    ........ddeeedd1ede1ddeedd...ddfddd...
    ........dddeedddddddddeedd..ddfdddfd..
    .......eeeddddddeeedddddd....fffdfdd..
    .....eeeedd11ddddddddd11dd...dddfddd..
    ....eeeeed111e111e111e111d....ddddede.
    ..eeeeeeedde1ee1eee1eee1ed.......eeee.
    .eeeeeeeeedd1e111e111e11de......eeeee.
    eeeeefeeeeeddd111d111dddeeeeeeeeeeeeee
    eeeeeeffeeeeedddddddddeeeeeeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee
    .eeeeeeeeeedddddeedddddeeeeeeeeeeeeee.
    ..eeeeeeeeedddddffdddddeeeeeeeeeeeee..
    ...eeeeeeeedddddffdddddeeeeeeeeeee....
    ....eeeeeeedddddffdddddeeeeeeeeee.....
    .......eeeedddffddffdddeeeeeeee.......
    .....eeeeeeeffddddddffeeeeeeee........
    ...eeeeeeeeeeddddddddeeeeeeeee........
    ..eeeeeeeeeeeeddddddeeeeeeeeee........
    ..eeeeeeeeeeeeddddddeeeeeeeeee........
    ..eeeeeeeeeeeeeddddeeeeeeeeeeee.......
    ..eeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
    .eeeeeeeeeeeee.....eeeeeeeeeeeeee.....
    ddeeeeeee...........eeeeeeeeeeeeee....
    edddeeee.............eeeeeeeeeeeee....
    dddedddd..............eeeeeeeeeeee....
    ......................eeeeeeeeeee.....
    ......................eeeeeeeeeee.....
    .......................dedddeeedded...
    .......................ddedddddedded..
    ........................ddddddddddded.
    `, SpriteKind.donkey)
let myTile = scene.getTile(1, 29)
scene.place(myTile, mySpritebottom)
let tile_list = scene.getTilesByType(9)
let dk = scene.getTile(5, 3)
scene.place(dk, donkeykong)
game.onUpdate(function () {
    mySpriteTop.setPosition(mySpritebottom.x, mySpritebottom.y - 8)
    if (mySpritebottom.bottom == tiles.tilemapRows() * tiles.tileWidth()) {
        game.reset()
    }
})
game.onUpdateInterval(1000, function () {
    donkeykong.setImage(img`
        .................eeeeeee..............
        ................eeeeeeeee.............
        ...............eeddeeeddee............
        ..............eeddddedddeee...........
        ..............edddddeddddeee..........
        .....ddd......eddd11d11dddeed.........
        ...dddfdd...ddeedd1ede1ddeeedd........
        ..dfdddfdd..ddeedddddddddeeddd........
        ..ddfdfff....ddddddeeeddddddeee.......
        ..dddfddd...dd11ddddddddd11ddeeee.....
        .ededddd....d111e111e111e111deeeee....
        .eeee.......de1eee1eee1ee1eddeeeeeee..
        .eeeee......ed11e111e111e1ddeeeeeeeee.
        eeeeeeeeeeeeeeddd111d111dddeeeeefeeeee
        eeeeeeeeeeeeeeeedddddddddeeeeeffeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeee
        .eeeeeeeeeeeeeedddddeedddddeeeeeeeeee.
        ..eeeeeeeeeeeeedddddffdddddeeeeeeeee..
        ....eeeeeeeeeeedddddffdddddeeeeeeee...
        .....eeeeeeeeeedddddffdddddeeeeeee....
        .......eeeeeeeedddffddffdddeeee.......
        ........eeeeeeeeffddddddffeeeeeee.....
        ........eeeeeeeeeddddddddeeeeeeeeee...
        ........eeeeeeeeeeddddddeeeeeeeeeeee..
        ........eeeeeeeeeeddddddeeeeeeeeeeee..
        .......eeeeeeeeeeeeddddeeeeeeeeeeeee..
        ......eeeeeeeeeeeeeeeeeeeeeeeeeeeeee..
        .....eeeeeeeeeeeeee.....eeeeeeeeeeeee.
        ....eeeeeeeeeeeeee...........eeeeeeedd
        ....eeeeeeeeeeeee.............eeeeddde
        ....eeeeeeeeeeee..............ddddeddd
        .....eeeeeeeeeee......................
        .....eeeeeeeeeee......................
        ...deddeeeddded.......................
        ..deddedddddedd.......................
        .deddddddddddd........................
        `)
    timer.after(500, function () {
        donkeykong.setImage(img`
            ..............eeeeeee.................
            .............eeeeeeeee................
            ............eeddeeeddee...............
            ...........eeedddeddddee..............
            ..........eeeddddeddddde..............
            .........deeddd11d11ddde......ddd.....
            ........ddeeedd1ede1ddeedd...ddfddd...
            ........dddeedddddddddeedd..ddfdddfd..
            .......eeeddddddeeedddddd....fffdfdd..
            .....eeeedd11ddddddddd11dd...dddfddd..
            ....eeeeed111e111e111e111d....ddddede.
            ..eeeeeeedde1ee1eee1eee1ed.......eeee.
            .eeeeeeeeedd1e111e111e11de......eeeee.
            eeeeefeeeeeddd111d111dddeeeeeeeeeeeeee
            eeeeeeffeeeeedddddddddeeeeeeeeeeeeeeee
            eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee
            eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee
            .eeeeeeeeeedddddeedddddeeeeeeeeeeeeee.
            ..eeeeeeeeedddddffdddddeeeeeeeeeeeee..
            ...eeeeeeeedddddffdddddeeeeeeeeeee....
            ....eeeeeeedddddffdddddeeeeeeeeee.....
            .......eeeedddffddffdddeeeeeeee.......
            .....eeeeeeeffddddddffeeeeeeee........
            ...eeeeeeeeeeddddddddeeeeeeeee........
            ..eeeeeeeeeeeeddddddeeeeeeeeee........
            ..eeeeeeeeeeeeddddddeeeeeeeeee........
            ..eeeeeeeeeeeeeddddeeeeeeeeeeee.......
            ..eeeeeeeeeeeeeeeeeeeeeeeeeeeeee......
            .eeeeeeeeeeeee.....eeeeeeeeeeeeee.....
            ddeeeeeee...........eeeeeeeeeeeeee....
            edddeeee.............eeeeeeeeeeeee....
            dddedddd..............eeeeeeeeeeee....
            ......................eeeeeeeeeee.....
            ......................eeeeeeeeeee.....
            .......................dedddeeedded...
            .......................ddedddddedded..
            ........................ddddddddddded.
            `)
    })
})
