scene.setTileMap(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    22222...............
    ...9.2222222222.....
    ...9...........22222
    ...9................
    ....................
    ....................
    ...9.........2222222
    fc.9..2222222.......
    222222..............
    ....................
    `, TileScale.Eight)
scene.setTile(2, img`
    2 2 2 2 2 2 2 2 
    . . . 2 2 . . . 
    . . . 2 2 . . . 
    . . 2 . . 2 . . 
    . 2 . . . . 2 . 
    . 2 . . . . 2 . 
    2 . . . . . . 2 
    2 2 2 2 2 2 2 2 
    `, true)
scene.setTile(9, img`
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    9 9 9 9 9 9 9 9 
    9 . . . . . . 9 
    `, false)
scene.setTile(12, img`
    c c c c c c c c 
    b c c c c c c b 
    c b b b b b b c 
    c c c c c c c c 
    b c c c c c c b 
    c b b b b b b c 
    c c c c c c c c 
    c c c c c c c c 
    `, false)
let mySpritebottom = sprites.create(img`
    . d d f f f . . 
    . d d d d d . . 
    2 2 8 2 2 8 2 . 
    2 8 5 8 8 5 2 . 
    d 8 8 8 8 8 d . 
    . 8 8 8 8 8 . . 
    . 8 8 . 8 8 . . 
    . e e . e e . . 
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySpritebottom)
controller.moveSprite(mySpritebottom, 50, 0)
let mySpriteTop = sprites.create(img`
    . . . . . . . . 
    . . . . . . . . 
    . . . . . . . . 
    . 2 2 2 1 . . . 
    . 2 2 2 2 2 2 2 
    . e e d d d . . 
    . d d f d f . . 
    . d d d d d d . 
    `, SpriteKind.Player)
let myTile = scene.getTile(0, 29)
scene.place(myTile, mySpritebottom)
game.onUpdate(function () {
    mySpriteTop.setPosition(mySpritebottom.x, mySpritebottom.y - 8)
})
